#!/usr/bin/env python3
import glob
import os
import re
import sys
from typing import Any

CWD = os.getcwd()
BASE = sys.argv[1]


def check_link(m: Any) -> str:
    link, pre, txt, post = m.groups()
    if not link and txt in links:
        return f'<a href="{links[txt]}">{pre}{txt}{post}</a>'
    return m.group(0)


os.chdir(BASE)

# Get list of generated HTML files and the class / method they belong to
links = {}
for f in glob.glob(os.path.join('generated', '*.html')):
    m = re.search(r'([A-Z]\w+)\.html$', f)
    if m:
        links[m.group(1)] = f.split(os.sep)[-1]
        continue

    m = re.search(r'([A-Z]\w+\.[a-z]\w+)\.html$', f)
    if m:
        links[m.group(1)] = f.split(os.sep)[-1]

# Get list of HTML files
html_files = []
for root, dirs, files in os.walk('.'):
    for file in files:
        if file.lower().endswith('.html'):
            html_files.append(os.path.join(root, file))

# Process HTML files
for file in html_files:
    with open(file, 'r') as html_file:
        txt = html_file.read()

        # Remove module names from hidden modules
        txt = re.sub(
            r'(">)singlestoredb\.(manager|connection)\.([\w\.]+</a>)', r'\1\3', txt,
        )

        # Fix class / method links
        txt = re.sub(
            r'(<a\s+[^>]+>)?(\s*<code[^>]*>\s*<span\s+class="pre">\s*)([\w\.]+)(\s*</span>\s*</code>)',
            check_link, txt,
        )

    with open(file, 'w') as html_file:
        html_file.write(txt)

with open(os.path.join('_static', 'custom.css'), 'w') as custom_css:
    with open(os.path.join(CWD, 'custom.css'), 'r') as input_css:
        custom_css.write(input_css.read().strip())
