#!/usr/bin/env python
# type: ignore
"""
Terminate deployments left behind by earlier test runs.

The test suite now sweeps what it creates (see ``utils.track()`` and the
hooks in ``conftest.py``), but a run that was killed -- or one from before
that sweep existed -- leaves live workspace groups, workspaces, clusters and
starter clusters behind, and they are billed until someone removes them.

Only names the test suite generates are considered, and the default is a dry
run::

    python -m singlestoredb.tests.cleanup_deployments
    python -m singlestoredb.tests.cleanup_deployments --yes

If the organization is visibly full of strays and this reports none, the names
are not in ``PATTERNS``. ``--show-unmatched`` lists every live deployment the
tool does not recognize, which is how an unconventionally named one gets found.

This tool is organization-wide, not run-scoped: it matches on names, and a
name says which suite made a deployment but not which run. A concurrent run's
fixtures look exactly like stranded ones. Age is the only thing separating
them, so ``--older-than`` defaults to a span longer than a full suite rather
than to zero -- raise it if your runs can take longer than that, and only
pass ``--older-than 0`` when you know nothing else is running.

For deployments the current process created, nothing here is needed: those
are tracked as they are created and swept per test class by ``conftest.py``,
which cannot see -- or touch -- another run's deployments.

Why strays keep appearing: that tracking, the per-class sweep and this script
all live on the ``versioned-management-api`` branch and nowhere else. A run
from ``main`` has only ``tearDownClass``, so a killed run or a ``setUpClass``
that raises leaks a workspace group permanently, and ``main`` still uses names
this script only knows through :data:`LEGACY_PATTERNS`. Until the sweep is on
the default branch, expect to run this by hand.
"""
import argparse
import datetime
import re
import sys
import warnings
from typing import Any
from typing import List
from typing import Optional
from typing import Tuple

import singlestoredb as s2


#: Hours a deployment must have existed before it is treated as stranded.
#: The slowest class creates three clusters with a 1200s wait each and then
#: terminates them the same way, so a full suite is comfortably inside this;
#: anything younger could belong to a run in progress.
DEFAULT_MIN_AGE_HOURS = 6.0

#: Names the suite generates. Anchored, because these run against a real
#: organization: a pattern that matched a name someone chose by hand would
#: terminate a deployment that is not ours.
PATTERNS = [
    # test_management_v1.py / test_management_v2.py fixtures
    re.compile(r'^(wg|ws|cl)-test-[A-Za-z0-9_-]+$'),
    re.compile(r'^starter-(ws|cl)-test-[A-Za-z0-9_-]+$'),
    # test_fusion.py fixtures
    re.compile(r'^[A-C] Fusion Testing [0-9a-f]+$'),
    re.compile(r'^[a-z]-fusion-cluster-[0-9a-f]+$'),
    re.compile(r'^jobs-fusion-[0-9a-f]+$'),
    re.compile(r'^stage-fusion-\d-[0-9a-f]+$'),
    # test_create_drop_workspace_group's subject. Hex covers the decimal
    # id(self) the test used to name it with, so groups stranded by older
    # runs -- which this pattern did not match, and which therefore piled up
    # invisibly -- are reaped too.
    re.compile(r'^Create WG Test [0-9a-f]+$'),
]

#: Names the suite used to generate. Kept separate so it is obvious what is
#: only here for cleanup, and matched all the same: a stranded deployment is
#: billed regardless of which revision made it, and ``main`` still creates
#: these -- it carries none of ``utils.track()``, the per-class sweep or this
#: script, so a run there leaks with nothing to reap it. Retire an entry once
#: no branch produces the name and the organization is clean of it.
LEGACY_PATTERNS = [
    # TestStageFusion's two workspace groups, before it moved to v2 clusters
    # named stage-fusion-<n>-<id> and then to the shared cluster pool
    re.compile(r'^Stage Fusion Testing \d [0-9a-f]+$'),
    # TestFilesFusion's workspace group, which nothing in the class ever
    # read; it creates no deployment at all now
    re.compile(r'^Files Fusion Testing [0-9a-f]+$'),
    # 'Group <hex>'. No revision of this repo generates this, so it is here
    # on the owner's say-so rather than by attribution. Eight hex characters
    # minimum, which is what the ones in the organization have: the bare
    # 'Group 1' / 'Group 2' that a person or the portal produces is a real
    # deployment someone is using, and a plain [0-9a-f]+ would match it.
    re.compile(r'^Group [0-9a-f]{8,}$'),
]


def is_test_deployment(name: Optional[str]) -> bool:
    """Was this name generated by the test suite, now or in the past?"""
    if not name:
        return False
    return any(x.match(name) for x in PATTERNS + LEGACY_PATTERNS)


def _age_hours(obj: Any) -> Optional[float]:
    """Hours since creation, or None if the API did not report it."""
    created = getattr(obj, 'created_at', None)
    if not isinstance(created, datetime.datetime):
        return None
    if created.tzinfo is None:
        # A naive timestamp from the API is UTC. Reading it as local time
        # would overstate the age by the offset, which is the direction that
        # sweeps a deployment a live run still owns.
        created = created.replace(tzinfo=datetime.timezone.utc)
    now = datetime.datetime.now(tz=datetime.timezone.utc)
    return (now - created).total_seconds() / 3600.0


def find_leftovers(
    older_than: float = DEFAULT_MIN_AGE_HOURS,
    include_unknown_age: bool = False,
) -> Tuple[List[Tuple[str, Any]], List[str], List[str]]:
    """
    List the live, test-named deployments in the current organization.

    Both API versions are asked: v1 owns workspace groups and workspaces,
    v2 owns clusters, and a suite that has run under either may have left
    something behind.

    Returns
    -------
    (List[Tuple[str, Any]], List[str], List[str])
        The deployments to sweep, labels for the ones held back by the age
        guard so the caller can say what it did not touch, and labels for the
        live deployments whose names :data:`PATTERNS` does not recognize.

        That third list is the answer to "the organization is full of strays
        and this tool says there are none". A test that names a deployment
        outside the conventions above is invisible here, so it accumulates
        silently -- which is exactly what ``Create WG Test <id(self)>`` did.
        Reporting the unrecognized names makes the next one findable.

    """
    found: List[Tuple[str, Any]] = []
    spared: List[str] = []
    unmatched: List[str] = []

    def keep(obj: Any) -> bool:
        name = getattr(obj, 'name', None)
        if getattr(obj, 'terminated_at', None) is not None:
            return False
        if not is_test_deployment(name):
            age = _age_hours(obj)
            unmatched.append(
                '{}{}'.format(
                    name or '<unnamed>',
                    '' if age is None else f' ({age:.1f}h old)',
                ),
            )
            return False

        # Age is the only thing separating a stranded deployment from one a
        # concurrent run is using right now: names carry a per-class random
        # id, not a per-run one, and a cluster name is capped at 32
        # characters, so there is no room to stamp a run id into it.
        age = _age_hours(obj)
        if age is None:
            if not include_unknown_age:
                spared.append(f'{name} (creation time not reported)')
                return False
            return True
        if older_than > 0 and age < older_than:
            spared.append(f'{name} ({age:.1f}h old)')
            return False
        return True

    try:
        clusters = s2.manage_clusters(version='v2')
    except Exception as exc:
        print(f'! Could not reach management API v2: {exc}', file=sys.stderr)
    else:
        for cluster in clusters.clusters:
            if keep(cluster):
                found.append((f'cluster {cluster.name} ({cluster.id})', cluster))
        for starter in clusters.starter_clusters:
            if keep(starter):
                found.append((
                    f'starter cluster {starter.name} ({starter.id})', starter,
                ))

    try:
        # v1 is deprecated, and asking for it here is the point: workspace
        # groups exist nowhere else, so the warning is noise on every run.
        with warnings.catch_warnings():
            warnings.filterwarnings(
                'ignore', category=DeprecationWarning,
                message='.*manage_workspaces.*',
            )
            workspaces = s2.manage_workspaces(version='v1')
    except Exception as exc:
        print(f'! Could not reach management API v1: {exc}', file=sys.stderr)
    else:
        for group in workspaces.workspace_groups:
            if keep(group):
                # The group takes its workspaces with it, so they are not
                # listed separately.
                found.append((
                    f'workspace group {group.name} ({group.id})', group,
                ))
        for starter in workspaces.starter_workspaces:
            if keep(starter):
                found.append((
                    f'starter workspace {starter.name} ({starter.id})', starter,
                ))

    return found, spared, unmatched


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[1])
    parser.add_argument(
        '--yes', action='store_true',
        help='actually terminate; without this the run only reports',
    )
    parser.add_argument(
        '--older-than', type=float, default=DEFAULT_MIN_AGE_HOURS,
        metavar='HOURS',
        help='only sweep deployments at least this old '
             f'(default: {DEFAULT_MIN_AGE_HOURS}). Pass 0 to sweep every '
             'match, which will terminate deployments a concurrent test run '
             'is still using',
    )
    parser.add_argument(
        '--include-unknown-age', action='store_true',
        help='also sweep matches whose creation time the API did not report '
             '(skipped by default, since an unknown age cannot be shown to '
             'be old enough)',
    )
    parser.add_argument(
        '--show-unmatched', action='store_true',
        help='also list the live deployments this tool does not recognize as '
             "the suite's, without touching them. Run this when the "
             'organization looks full of strays but the sweep finds none: a '
             'test that names a deployment outside the conventions in '
             'PATTERNS is invisible here until its name is added',
    )
    args = parser.parse_args(argv)

    leftovers, spared, unmatched = find_leftovers(
        args.older_than, args.include_unknown_age,
    )

    if args.show_unmatched:
        if unmatched:
            print(
                f'{len(unmatched)} live deployment(s) not recognized as the '
                "suite's, and so never swept:",
            )
            for label in sorted(unmatched):
                print(f'  ? {label}')
            print(
                '\nIf one of these was made by a test, add its name to '
                'PATTERNS in this module.\n',
            )
        else:
            print('Every live deployment is recognized by PATTERNS.\n')

    if spared:
        print(
            f'{len(spared)} match(es) left alone, too new to be sure no '
            'run owns them:',
        )
        for label in spared:
            print(f'  - {label}')
        print()

    if not leftovers:
        print('No leftover test deployments found.')
        return 0

    print(f'{len(leftovers)} leftover test deployment(s):')
    for label, _ in leftovers:
        print(f'  - {label}')

    if not args.yes:
        print('\nDry run; pass --yes to terminate these.')
        return 0

    from singlestoredb.tests import utils

    failed = 0
    for label, obj in leftovers:
        try:
            utils.terminate(obj)
        except Exception as exc:
            failed += 1
            print(f'✗ {label}: {exc}')
        else:
            print(f'✓ terminated {label}')

    return 1 if failed else 0


if __name__ == '__main__':
    sys.exit(main())
