#!/usr/bin/env python
from __future__ import annotations

import os
import re
import sys


BASE = sys.argv[1]

# Get list of HTML files
html_files = []
for root, dirs, files in os.walk(BASE):
    for file in files:
        if file.lower().endswith('.html'):
            html_files.append(os.path.join(root, file))

# Process HTML files
for file in html_files:
    with open(file, 'r') as html_file:
        txt = html_file.read()

        # Remove module names from hidden modules
        txt = re.sub(
            r'(">)singlestore\.(manager|connection)\.([\w\.]+</a>)', r'\1\3', txt,
        )

    with open(file, 'w') as html_file:
        html_file.write(txt)
